name: MultiEnderChest
main: com.troidworks.bukkit.multiEnderChest.MultiEnderChest
version: 0.3
permissions:
  multienderchest.use:
    description: Allows use extended ender chest space.
    default: op